# Generated by Django 6.0.4 on 2026-05-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOSEN', 'Dosen')], default='DOSEN', max_length=15),
        ),
    ]
