# Generated by Django 6.0.4 on 2026-05-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KelasAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True, verbose_name='Nama Kelas')),
                ('program_studi', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('jumlah_mahasiswa', models.IntegerField(default=0, verbose_name='Estimasi Jumlah Mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=20, unique=True, verbose_name='Kode Matkul')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Mata Kuliah')),
                ('sks', models.IntegerField(verbose_name='Bobot SKS')),
            ],
        ),
        migrations.CreateModel(
            name='Ruangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True, verbose_name='Nama Ruangan')),
                ('kapasitas', models.IntegerField(verbose_name='Kapasitas Maksimal (Orang)')),
                ('is_hybrid', models.BooleanField(default=False, verbose_name='Fasilitas Hybrid (Kamera/Proyektor)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
            ],
        ),
    ]
