# Generated by Django 6.0.4 on 2026-05-18 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HariLibur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(unique=True, verbose_name='Tanggal Libur')),
                ('keterangan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BaseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('hari', models.IntegerField(choices=[(1, 'Senin'), (2, 'Selasa'), (3, 'Rabu'), (4, 'Kamis'), (5, 'Jumat'), (6, 'Sabtu'), (7, 'Minggu')])),
                ('dosen_pengampu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profildosen')),
                ('kelas', models.ManyToManyField(to='master_data.kelasakademik')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.matakuliah')),
                ('ruangan_default', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ruangan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActualSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Terjadwal'), ('COMPLETED', 'Selesai'), ('CANCELED', 'Dibatalkan'), ('RESCHEDULED', 'Dijadwalkan Ulang')], default='SCHEDULED', max_length=15)),
                ('dosen_pengampu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profildosen')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.matakuliah')),
                ('ruangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ruangan')),
                ('base_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actual_sessions', to='schedules.baseschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PengajuanReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_baru', models.DateField()),
                ('jam_mulai_baru', models.TimeField()),
                ('jam_selesai_baru', models.TimeField(blank=True, null=True)),
                ('tipe_pengganti', models.CharField(choices=[('OFFLINE', 'Offline (Butuh Ruangan)'), ('ONLINE', 'Online (Tanpa Ruangan)')], default='OFFLINE', max_length=10)),
                ('alasan', models.TextField(blank=True, help_text='Alasan pemindahan jadwal')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=10)),
                ('catatan_admin', models.TextField(blank=True, help_text='Alasan penolakan dari Admin', null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diupdate_pada', models.DateTimeField(auto_now=True)),
                ('ruangan_baru', models.ForeignKey(blank=True, help_text='Kosong jika Online', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ruangan')),
                ('sesi_lama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengajuan_reschedule', to='schedules.actualsession')),
            ],
        ),
        migrations.CreateModel(
            name='SessionKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('OFFLINE', 'Offline di Ruangan'), ('ONLINE', 'Online / Daring')], default='OFFLINE', max_length=10)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.kelasakademik')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta_kelas', to='schedules.actualsession')),
            ],
        ),
    ]
